config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :invites
  resources :conversations
  resources :conversations do 
    resources :messages
  end
  
  
  get 'home/index'

  resources :categories
  devise_for :businesses
  devise_for :users, controllers: {registrations: "registrations"}
  resources :businesses do
    resources :events
  end

  resources :users do
    resource :profile
    resources :invites
    member do
      post :follow
      delete :unfollow
      get :following
      get :followers
    end
  end

  resources :events do 
    resources :comments
    resources :invites
    collection do
      get :search
    end
  end
  resources :comments


  resources :places


  root "events#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
    @business = @business.places
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:company_name, :slug)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.haml
= simple_form_for(@business) do |f|
  = f.error_notification

  .form-inputs
    = f.input :company_name
    = f.input :slug

  .form-actions
    = f.button :submit

app/views/businesses/edit.html.haml
%h1 Editing business

= render 'form'

= link_to 'Show', @business
\|
= link_to 'Back', businesses_path

app/views/businesses/index.html.haml
%h1 Listing businesses

%table
  %thead
    %tr
      %th Company name
      %th Slug
      %th
      %th
      %th

  %tbody
    - @businesses.each do |business|
      %tr
        %td= business.company_name
        %td= business.slug
        %td= link_to 'Show', business
        %td= link_to 'Edit', edit_business_path(business)
        %td= link_to 'Destroy', business, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Business', new_business_path

app/views/businesses/new.html.haml
%h1 New business

= render 'form'

= link_to 'Back', businesses_path

app/views/businesses/show.html.haml
%p#notice= notice

%p
  %b Company name:
  = @business.company_name
%p
  %b Slug:
  = @business.slug

= link_to 'Edit', edit_business_path(@business)
\|
= link_to 'Back', businesses_path