config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :invites
  resources :conversations
  resources :conversations do 
    resources :messages
  end
  
  
  get 'home/index'

  resources :categories
  devise_for :businesses
  devise_for :users, controllers: {registrations: "registrations"}
  resources :businesses do
    resources :events
  end

  resources :users do
    resource :profile
    resources :invites
    member do
      post :follow
      delete :unfollow
      get :following
      get :followers
    end
  end

  resources :events do 
    resources :comments
    resources :invites
    collection do
      get :search
    end
  end
  resources :comments


  resources :places


  root "events#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :user_id, :event_id, presence: true
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, except: [:index, :edit, :update, :destroy]
  before_action :set_invite, only: [:show, :edit, :update, :destroy]



  def index
    @user = current_user
    @invites = @user.invites
  end

  def new
    @users = User.all
  end

  def create
    invites = []
    params[:user_ids].each do |user_id, value|
      invites << (@event.invites.build(user_id: user_id)) if value == "1"
    end
    if invites.any? { |invite| invite.invalid? }
      render :new
    else
      invites.each { |invite| invite.save }
      i_l = invites.length 
      flash[:success] = "#{i_l} " + "invite".pluralize(i_l) + " sent!"
      redirect_to @event
    end
  end

  def edit
    @user = User.find_by(id: params[:user_id])
    @invite = Invite.find_by(id: params[:id])
    @event = @invite.event
  end

  def update
    @user = User.find_by(id: params[:user_id])
    @invite = Invite.find_by(id: params[:id])
    if @invite.update_attributes(update_invite_params)
      flash[:success] = "Reply updated!"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    # Invite found by host_or_guest_user before filter.
    @invite.destroy
    flash[:success] = "Invite canceled"
    redirect_to request.referrer || root_url
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_invite
      @invite = Invite.find(params[:id])
    end

    def set_event
      @event = Event.friendly.find(params[:event_id])
    end

    def update_invite_params
      params.require(:invite).permit(:status)
    end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_form.html.haml
= simple_form_for(@invite) do |f|
  = f.error_notification

  .form-inputs
    = f.input :status
    = f.association :user
    = f.association :event

  .form-actions
    = f.button :submit

app/views/invites/_invite.html.erb
<li>
  <span class="event_link">
    <%= link_to invite.event.title, event_path(invite.event) %>
  </span>
  <span>
    Hosted by: 
    <%= link_to invite.event.business, user_path(invite.event.business) %>
  </span>
  <span>Current reply: <%= invite.status %></span>
  <span class="change_links">
    <%= link_to "change reply", edit_user_invite_path(invite.user, invite) %>
    <%= link_to "delete", invite, method: :delete,
                                  data: { confirm: "Are you sure?" } %>
  </span>
</li>

app/views/invites/edit.html.erb
<div class="row event_show">
  <div class="col-md-8 col-md-offset-2" >
    <h1><%= @event.title %></h1>
    <h2 class="host">
      Hosted by: 
      <%= link_to @event.business, @event.business %>
    </h2>
    <p class="description"><%= @event.description %></p>
    <span class="event_date">
      <%= "#{@event.start_date}, Begins on " %>
    </span>
    <span class="timestamp">
      Created <%= time_ago_in_words(@event.created_at) %> ago.
    </span>
    <span class="current_reply">Current reply: <%= @invite.status %></span>
    <span class="reply_form">
      <%= form_for(:invite, url: user_invite_path(@user, @invite),
                            method: :patch) do |f| %>
        Change reply to: 

        <%= f.hidden_field :status, value: @invite.status %>

        <%= f.label :status, class: "radio-inline" do %>
          <%= f.radio_button :status, "yes", class: "radio-inline" %>
          <span>yes</span>
        <% end %>

        <%= f.label :status, class: "radio-inline" do %>
          <%= f.radio_button :status, "no", class: "radio-inline" %>
          <span>no</span>
        <% end %>

        <%= f.submit "Submit", class: "btn btn-primary reply_submit" %>
      <% end %>
    </span>
  </div>
</div>

app/views/invites/edit.html.haml
%h1 Editing invite

= render 'form'

= link_to 'Show', @invite
\|
= link_to 'Back', invites_path

app/views/invites/index.html.erb
<div class="row">
  <%= render "shared/user_sidebar" %>
  <div class="col-md-8">
    <h3>Invites (<%= @invites.count %>)</h3>
    <ul class="invites">
      <% if @invites.none? %>
        <li>Currently invited to no events.</li>
      <% end %>
      <%= render @invites %>
    </ul>
  </div>
</div>

app/views/invites/index.html.haml
%h1 Listing invites

%table
  %thead
    %tr
      %th Status
      %th User
      %th Event
      %th
      %th
      %th

  %tbody
    - @invites.each do |invite|
      %tr
        %td= invite.status
        %td= invite.user
        %td= invite.event
        %td= link_to 'Show', invite
        %td= link_to 'Edit', edit_invite_path(invite)
        %td= link_to 'Destroy', invite, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Invite', new_invite_path

app/views/invites/new.html.erb
<% provide(:title, "Invite users") %>
<h1>Invite Users</h1>

<%= form_tag [@event, @event.invites.new] do %>
  <ul class="users">
    <% @users.each do |user| %>
      <%= hidden_field_tag :event_id, @event %>
      <%= render partial: "shared/user_invite", locals: { user: user } %>
    <% end %>
  </ul>

  <%= submit_tag "Send invites", class: "btn btn-primary" %>
<% end %>

app/views/invites/new.html.haml
%h1 New invite

= render 'form'

= link_to 'Back', invites_path

app/views/invites/show.html.haml
%p#notice= notice

%p
  %b Status:
  = @invite.status
%p
  %b User:
  = @invite.user
%p
  %b Event:
  = @invite.event

= link_to 'Edit', edit_invite_path(@invite)
\|
= link_to 'Back', invites_path