config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :invites
  resources :conversations
  resources :conversations do 
    resources :messages
  end
  
  
  get 'home/index'

  resources :categories
  devise_for :businesses
  devise_for :users, controllers: {registrations: "registrations"}
  resources :businesses do
    resources :events
  end

  resources :users do
    resource :profile
    resources :invites
    member do
      post :follow
      delete :unfollow
      get :following
      get :followers
    end
  end

  resources :events do 
    resources :comments
    resources :invites
    collection do
      get :search
    end
  end
  resources :comments


  resources :places


  root "events#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  after_create :build_stuff
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, format: { without: /^((http|https):\/\/)[a-z0-9]*(\.?[a-z0-9]+)\.[a-z]{2,5}(:[0-9]{1,5})?(\/.)?$/ix, multiline: true }

  has_one :profile, as: :profileable, dependent: :destroy

  has_one :place, as: :placeable
  accepts_nested_attributes_for :place, reject_if: :all_blank

  validates :name, presence: true

  has_many :subscriptions, foreign_key: :follower_id, dependent: :destroy
  has_many :leaders, through: :subscriptions

  has_many :reverve_subscriptions, foreign_key: :leader_id, class_name: "Subscription", dependent: :destroy
  has_many :followers, through: :reverve_subscriptions

  has_many :sent_messages, class_name: "Conversation", foreign_key: "sender_id"
  has_many :received_messages, class_name: "Conversation", foreign_key: "recipient_id"
  has_many :messages

  # invite invitations
  has_many :invites
  has_many :events_as_guest, through: :invites, source: :event


  def following?(leader)
    leaders.include? leader
  end

  def follow!(leader)
    if leader != self && !following?(leader)
      leaders << leader
    end
  end

  def unfollow!(leader)
    if leader != self && following?(leader)
      subscriptions.find_by(leader_id: leader.id).destroy
    end
  end

  def timeline_user_ids
    leader_ids + [id]
  end

  def build_stuff
    self.create_profile
    self.create_place
  end

  # Event Methods

  def upcoming_events
    self.events_as_guest.upcoming
  end

  def previous_events
    self.events_as_guest.past
  end

  def attending?(event)
    event.guests.include?(self)
  end

  def attend!(event)
    self.invites.create!(attended_event_id: event.id)
  end

  def cancel!(event)
    self.invites.find_by(attended_event_id: event.id).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :following, :followers]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    #@events_as_host = @user.events_as_host
    @attending_events = @user.events_as_guest.where('invites.status' => 'yes')
  end

  # GET /users/new
  def new
    @user = User.new
    @user = @user.place_build
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def following
    @users = @user.leaders.all
    render :index
  end

  def followers
    @users = @user.followers.all
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :slug, place_attributes: [:title, :street, :city, :state, :country, :zipcode])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.haml
= link_to "Follow", follow_user_path(@user), class: "btn btn-success", method: :post, remote: true

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    - if @user_update
      = f.input :name
      = f.input :slug
    - else

      = f.simple_fields_for :place do |p|
        = p.input :title
        = p.input :street
        = p.input :city
        = p.input :state
        = p.input :country
        = p.input :zipcode

  .form-actions
    = f.button :submit, "Update"

app/views/users/_profile.html.erb
<script>

$(document).ready(function () {
  $('#horizontalTab').easyResponsiveTabs({
    type: 'default', //Types: default, vertical, accordion
    width: 'auto', //auto or any width like 600px
    fit: true,   // 100% fit in a container
    closed: 'accordion', // Start closed if in accordion view
    activate: function(event) { // Callback function if tab is switched
      var $tab = $(this);
      var $info = $('#tabInfo');
      var $name = $('span', $info);
      $name.text($tab.text());
      $info.show();
    }
  });

  $('#verticalTab').easyResponsiveTabs({
    type: 'vertical',
    width: 'auto',
    fit: true
  });
});
</script>

<h1><%= "##{@user.name} Profile" %></h1>
<div class="content">
  <div class="sap_tabs">
  <div id="horizontalTab" ">
    <div class="portfolio-grid">
    <div class="col-md-4">
      <ul class="resp-tabs-list">
      <% - if @user.profile.image.present? %>
        <%= image_tag(@user.profile.image_url)%>
      <% else %>
        <%= image_tag("http://placehold.it/350x250", alt: "" )%>
      <% end %>
      <li class="resp-tab-item" aria-controls="tab_item-0" role="tab"><span><%= link_to "Basic Details", "" %></span></li>
      <li class="resp-tab-item" aria-controls="tab_item-1" role="tab"><span>Interests</span></li>
      <li class="resp-tab-item" aria-controls="tab_item-2" role="tab"><span>Work & Play</span></li>
      <li class="resp-tab-item" aria-controls="tab_item-3" role="tab"><span>Social Life</span></li>
      
      <li class="resp-tab-item" aria-controls="tab_item-4" role="tab"><span>Settings</span></li>
      <div class="clear"></div>
      </ul>   
    </div>
    <div class="col-md-8">
      <div class="resp-tabs-container">

      <div class="tab-1 resp-tab-content" aria-labelledby="tab_item-0">
        <div class="profile-content">
        
        
        <p><%= render 'users/stars' %></p>
        <% if current_user != @user %>
          <p><%= link_to "Message me!", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: :pos %></p>
        <% end %>
        <h3>First Name</h3>  
        <p><%= @user.profile.first_name %></p>
        <h3>Last Name</h3>
        <p><%= @user.profile.last_name %></p>
        <h3>Date Of Birth</h3>
        <p><%= @user.profile.date_of_birth %></p>
        <h3>Email</h3>
        <p><%= @user.email %></p>
        <h3>Contact Number</h3> 
        <p><%= @user.profile.contact_number %></p>
        <h3>Gender</h3> 
        <p><%= @user.profile.gender %></p>
        </div>
        <div class="update">
          <%= link_to "Update", edit_user_profile_path(@user) %>
        </div>
        <div class="clear"></div>
      </div>

      <div class="tab-1 resp-tab-content" aria-labelledby="tab_item-1">
        <div class="interests">
        <h3>Interested in</h3>
        <div class="single-bottom">
          <h3>Interest</h3>
          <p><%= @user.profile.interest %></p>
          <h3>Favourite Quote</h3>
          <p><%= @user.profile.favourite_quote %></p>
          <h3>About You</h3>
          <p><%= @user.profile.about_me %></p>
        </div>
        </div>
        <div class="update">
          <a href="#">Update</a>
        </div>
        <div class="clear"></div>                     
      </div>

      <div class="tab-1 resp-tab-content" aria-labelledby="tab_item-2">
        <div class="work-play">
        <h3>Location</h3>

        <h3>Say Something about you home town</h3>
        <p><%= @user.place.title %></p>
        <h3>Street</h3>
        <p><%= @user.place.street %>
        <h3>City</h3>
        <p><%= @user.place.city %>
        <h3>State/Province</h3>
        <p><%= @user.place.state %>
        <h3>Country</h3>
        <p><%= @user.place.country %></p>
        <h3>Zipcode</h3>
        <p><%= @user.place.zipcode %></p>

        <div class="update">
          <%= link_to "Update", edit_user_path(@user) %>
        </div>
        <div class="clear"></div>
        </div>
      </div>

      <div class="tab-1 resp-tab-content" aria-labelledby="tab_item-3">
        <div class="social-life">
        <h3>Social Profile</h3>
        <h4>We can automatically retrieve most facebook, twitter and linkedin profiles based on email address..</h4>  
          <p>Would you like to import social profiles now??  You can change this later.</p>
        <a href="#">Not Now</a>
        <a href="#">Yes</a>
        </div>
      </div>

                    
      <div class="tab-1 resp-tab-content" aria-labelledby="tab_item-4">
        <div class="work-play">
        <h3>Settings</h3>
        <h4>Profile Name</h4>

<div class="row">
  <%= render "shared/user_sidebar" %>
  <div class="col-md-4">
    <h3>Hosted events (<%#= @events_as_host.count %>)</h3>
    <ol class="events">
      <%# if @events_as_host.none? %>
        <li>Currently hosting no events.</li>
      <%# end %>
      <%#= render @events_as_host %>
    </ol>
  </div>
  <div class="col-md-4">
    <h3>Attending events (<%= @attending_events.count %>)</h3>
    <ol class="events">
      <% if @attending_events.none? %>
        <li>Currently attending no events.</li>
      <% end %>
      <%= render @attending_events %>
    </ol>
  </div>
</div>


        <div class="update">
          <a href="#">Update</a>
        </div>
          <div class="clear"></div>
        </div>                  
        </div>  
      </div>

      <div class="clear"></div>
    </div>
  
    </div>
  </div>
  </div>
</div>

app/views/users/_stars.html.haml
- if @user ||= current_user
  .stars
    = link_to following_user_path() do 
      %strong#following.stat
        = @user.leaders.count
      following
    = link_to followers_user_path() do 
      %strong#followers.stat
        = @user.followers.count
      followers 

- if current_user != @user
  #follow_form
    - unless current_user.following?(@user)
      = render 'users/follow'
    - else
      = render 'users/unfollow'

app/views/users/_unfollow.html.haml
= link_to "unFollow", unfollow_user_path(@user), class: "btn btn-default", method: :delete, remote: true 

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/follow.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/users/index.html.haml
%h1 Party Rockers
.row
  - @users.each do |user|
    - if user.id != current_user.id
      .item.col-sm-4
        - if user.profile.image.present?
          = image_tag(user.profile.image_url)
        - else
          =  image_tag "http://placehold.it/350x250", alt: ""
        %p= link_to user.name, user
        %p= link_to "Start a conversation with me!", conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post
     

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
.row
  = render 'profile' 

  .clearfix

app/views/users/unfollow.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');