config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :invites
  resources :conversations
  resources :conversations do 
    resources :messages
  end
  
  
  get 'home/index'

  resources :categories
  devise_for :businesses
  devise_for :users, controllers: {registrations: "registrations"}
  resources :businesses do
    resources :events
  end

  resources :users do
    resource :profile
    resources :invites
    member do
      post :follow
      delete :unfollow
      get :following
      get :followers
    end
  end

  resources :events do 
    resources :comments
    resources :invites
    collection do
      get :search
    end
  end
  resources :comments


  resources :places


  root "events#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord

  # ordering
  default_scope -> {order(start_date: "DESC")}

  # validation
  validate :event_start_cannot_be_in_the_part

  #has_many :reviews
  belongs_to :category
  
  mount_uploader :image, ImageUploader
  
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]

  def slug_candidates
  	[
  	 :title,
  	 [:title, :created_at]
  	]
  end

  belongs_to :business
  has_one :place, as: :placeable
  accepts_nested_attributes_for :place, reject_if: :all_blank

  has_many :comments

  has_many :invites, dependent: :destroy
  has_many :guests, through: :invites, source: :user

  scope :upcoming, -> { where("start_date >= ?", Date.today).order('start_date ASC') }
  scope :past, -> { where("end_date < ?", Date.today).order('end_date DESC') }
  scope :current_events, -> { where("start_date  == ?", Date.today)}

  def event_start_cannot_be_in_the_part
    errors.add(:start_date, "can't be in the past") if !start_date.blank? and start_date < Date.today
  end

  def self.search(params)
    events = Event.where(id: params[:category].to_i)
    events = events.where("title like ? or description like ?", "%#{params[:search]}%", "%#{params[:search]}%")
    events = events.place.near(params[:location], 20) if params[:location].present?
    events
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_business!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  #before_action :set_business, only: [:new, :create, :edit, :update, :destroy]


  # GET /events
  # GET /events.json
  def index
    #user_ids = current_user.timeline_user_ids
    #show by location
    #visitor_latitude = request.location.latitude 
    #visitor_longitude = request.location.latitude
    #@events = Event.near([visitor_latitude, visitor_longitude], 20)

    if params[:current_events]
      @events = Event.current_events.all
    elsif params[:upcoming]
      @events = Event.upcoming.all
    elsif params[:past]
      @events = Event.past.all
    else
      @events = Event.all
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    @event_place = @event.build_place

    @can_moderate = (current_business == @event.business)
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.business = current_business

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    redirect_to root_path if current_business != @event.business
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @events = Event.search(params)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.friendly.find(params[:id])
    end

    def event_owner!
      if business_signed_in?
        if @event.business_id != current_user.id
          redirect_to event_path
          flash[:notice] = 'You do not have enough permissions to do this'
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start_date, :end_date, :description, :image, :image_cache, :slug,
        place_attributes: [:street, :city, :state, :country, :zipcode])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.haml
%article.col-md-4
  %h5
    = link_to truncate(event.title, length: 50), event
  - if event.image.present?
    = image_tag(event.image_url, class: "img-rounded")
  - else
    = image_tag("http://placehold.it/350x250", class: "img-rounded")
  %p
    by
    = link_to "#{event.business}", event.business
  %p.small
    %strong
      Date:
    = fa_icon("clock") + event.start_date.strftime("%v")
    to
    = event.end_date.strftime("%v")
  %p.small
    %strong
      Time:
    = fa_icon("fa-clock") + event.start_date.strftime("%I:%M %P")
    to
    = event.end_date.strftime("%I:%M %P")
  %blockquote
    .small= event.place.street
    .small= "#{event.place.city}" 
    .small= "#{event.place.state}"
    .small= "#{event.place.country}"

app/views/events/_form.html.haml
= simple_form_for(@event) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :start_date, as: :datetime
    = f.input :end_date, as: :datetime
    = f.association :category
    = f.input :description

    = f.simple_fields_for :place do |p|
      = p.input :street
      = p.input :city
      = p.input :state
      = p.input :country
      = p.input :zipcode
    = @event.image_url if @event.image?
    = f.input :image
    = f.input :image_cache, as: :hidden
  .form-actions
    = f.button :submit

app/views/events/edit.html.haml
%h1 Editing event

= render 'form', business: @business, event: @event

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
%section
  = params.inspect
  %section.col-lg-12.col-md-12
    %h1 Upcoming Events
    %p= link_to "Plan Business", home_index_path

    - if business_signed_in?
      = link_to 'Create A New Event', new_business_event_path(current_business)


    .btn-group.btn-group-justified
      = link_to "Today", events_path(:current_events => true), class: "btn btn-info btn-sm"
      = link_to "Upcoming", events_path(:upcoming => true), class: "btn btn-info btn-sm" 
      = link_to "Past", events_path(:past => true), class: "btn btn-info btn-sm" 

  %section.col-lg-12.col-md-12
    = render @events

app/views/events/indx.html.erb
<article class="post  event-27137 ">
    <div class="event_img"> 
       <a href="https://demo.templatic.com/eventum/city/new-york/eventjames-darren-music-sal-richards-comedy/">
       <%= image_tag "img10.pjg", itemprop:"image", alt: "", title: "event-(16)" %>
       </a>
    </div>
    <div class="entry">
        <!--start post type title -->
        <div class="event-wrapper">
            <div class="event-title">
                <span class="date"> 08<span>Jul</span></span>
        <h2 class="">
            <a itemprop="url" href="" title="James Darren (music) &amp; Sal Richards (comedy)" rel="bookmark">James Darren (music) &amp; Sal Richards (comedy)</a></h2>
        <div class="listing_rating">
            <div class="directory_rating_row"><span class="single_rating"> <i class="rating-on"></i><i class="rating-on"></i><i class="rating-on"></i><i class="rating-on"></i><i class="rating-on"></i> </span></div>
        </div>
    </div>
    <!--end post type title -->
    <!-- Entry details start -->
    <div class="entry-details">
        <p class="address" itemprop="address">222-05 56th Avenue Bayside, NY 11364</p><p class="event_date"><span><span itemprop="startDate" content="2014-07-08T15:00">Jul 8, 2014</span> To <span itemprop="endDate" content="2019-07-08T17:00">Jul 8, 2019</span></span></p><p class="time"><span>3:00 pm To 5:00 pm</span></p><!--googleoff: all--><p class="phone">+86 10 6538 5537</p><!--googleon: all--> </div>
    </div>

    <!--Start Post Content -->
    <div class="rev_pin">
        <ul> 
            <li class="favourite">
               <span id="tmplfavorite_27137" class="fav fav_27137">
               <a href="javascript:void(0);" data-reveal-id="tmpl_reg_login_container" id="tmpl_login_frm_27137" data-id="27137" class="addtofav  small_btn" onclick="javascript:addToFavourite('27137','add');">Add to favorites</a></span>
            </li>
                         
            <li class="review"> <a id="reviews_show" href="https://demo.templatic.com/eventum/city/new-york/event/james-darren-music-sal-richards-comedy/#comments">8 &nbsp;</a></li>
             
            <li class="pinpoint"><a id="pinpoint_27137" class="ping" href="https://demo.templatic.com/eventum/city/new-york/ecategory/events/#map_canvas">Pinpoint</a></li>               
        </ul>
    </div>                         
</div>
</article>

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/search.html.haml
%section
  %section.col-lg-12.col-md-12
    %h1 Events Next You

    - if business_signed_in?
      = link_to 'Create A New Event', new_business_event_path(current_business)

  %section.col-lg-12.col-md-12
    = render @events

app/views/events/show.html.erb
<div class="row event_show">
  <aside class="col-md-2">
    <section class="invite_info">
      <h1>Invites(<%= @event.invites.count %>)</h1>
      <% if current_user %>
        <%= link_to "Invite users", new_event_invite_path(@event) %>
      <% end %>
    </section>
    <section>
      <h3>Attending (<%= @event.guests.where('invites.status' => 'yes').count %>)</h3>
      <ul>
        <% @event.guests.where('invites.status' => 'yes').each do |guest| %>
          <span class="invite_border"></span>
          <li><%= link_to guest.name, user_path(guest) %></li>
          <% if current_user %>
            <li>
              <%= link_to "uninvite",
                  invite_path(guest.invites.find_by(event_id: @event.id)),
                  method: :delete %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </section>
    <section>
      <h3>Not Going: (<%= @event.guests.where('invites.status' => 'no').count %>)</h3>
      <ul>
        <% @event.guests.where('invites.status' => 'no').each do |guest| %>
          <span class="invite_border"></span>
          <li><%= link_to guest.name, user_path(guest) %></li>
          <% if current_user %>
            <li>
              <%= link_to "uninvite",
                  invite_path(guest.invites.find_by(event_id: @event.id)),
                  method: :delete %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </section>
    <section>
      <h3>
        Undecided (<%= @event.guests.where('invites.status' => 'none').count %>)
      </h3>
      <ul>
        <% @event.guests.where('invites.status' => 'none').each do |guest| %>
          <span class="invite_border"></span>
          <li><%= link_to guest.name, user_path(guest) %></li>
          <% if current_user == @event.host %>
            <li>
              <%= link_to "uninvite",
                  invite_path(guest.invites.find_by(event_id: @event.id)),
                  method: :delete %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </section>
  </aside>
  <div class="col-md-6 col-md-offset-1" >
    <h1><%= @event.business %></h1>
    <h2 class="host">
      Hosted by: 
      <%= link_to @event.business, @event.business %>
    </h2>
    <p class="description"><%= @event.description %></p>
    <span class="event_date">
      <%= "#{@event.start_date}, Begins on " %>
    </span>
    <span class="timestamp">
      Created <%= time_ago_in_words(@event.created_at) %> ago.
      <% if current_user == @event.business %>
        <%= link_to "delete", @event, method: :delete,
                                      data: { confirm: "Are you sure?" } %>
      <% end %>
    </span>
  </div>
</div>

app/views/events/show.html.haml
%h2
  = @event.title

%p.thumbnail
  - if @event.image.present?
    = image_tag(@event.image_url)
  - else
    = image_tag "http://placehold.it/850x400", alt: "placehold"
.row
  .col-md-6
    %h3 Date
    %blockquote
      %p
        %b Start: 
        = @event.start_date
      %p
        %b End: 
        = @event.end_date
      %p
        %b Organizer:
        = @event.business

  .col-md-6
    %h3 Place
    %blockquote
      %p
        = @event.place.street 
      %p
        = "#{@event.place.city}, #{@event.place.state}"
      %p 
        %Country
        = @event.place.country
        = @event.place.zipcode
  .col-md-12
    %p= sanitize @event.description

= link_to 'Edit', edit_business_event_path(@event)
\|
= link_to 'Back', events_path


.comments_form
  = render 'comments/form'

.comments_list
  - if @event.comments.blank?
    %h3 No comments just yet, would you like to add the first!
  - else
    = render @event.comments.includes(:user)